version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 5s
            timeout: 10s
            retries: 5
        networks:
            - internal

    test:
        build:
            context: ..
            dockerfile: Dockerfile
            target: test
        depends_on:
            rabbitmq:
                condition: service_healthy
        networks:
            - internal

    worker:
        build:
            context: ..
            dockerfile: Dockerfile
            target: worker
        depends_on:
            - test  # Ждёт завершения тестов
        networks:
            - internal

networks:
    internal:
