version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - internal

  server:
    build:
      context: ..
      dockerfile: Dockerfile
      target: server
    networks:
      - internal
    depends_on:
      rabbitmq:
        condition: service_healthy

  integration-test:
    build:
      context: ..
      dockerfile: Dockerfile
      target: integration-test
    depends_on:
      server:
        condition: service_started
    networks:
      - internal

networks:
  internal:
