{
 "title": "Distributed Job Scheduling",
 "time": { "from": "2025-05-16T02:09:07.690Z", "to": "2025-05-16T14:09:07.690Z" },
 "panels": [
  {
   "title": "Completed jobs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "job_completed_total", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Submitted Jobs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 0 },
   "targets": [
    { "expr": "job_submitted_total", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Available workers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "worker_registered_total", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Heart Beats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "rate(worker_heartbeats_total[1m])",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}