services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MODE=test

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MODE=test

  test-runner:
    image: golang:1.21
    depends_on:
      - server
      - worker
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["go", "test", "-v", "./server/messaging/tests"]
