name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  terraform-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Initialize Terraform
        working-directory: terraform-local
        run: terraform init
      - name: Terraform Apply
        working-directory: terraform-local
        run: find .terraform -type f -exec chmod +x {} \; &&
             terraform apply -auto-approve
      - name: Wait for RabbitMQ to be healthy
        run: |
          echo "Waiting for RabbitMQ to be healthy..."
          for i in {1..20}; do
            if docker exec rabbitmq rabbitmq-diagnostics -q check_port_connectivity; then
              echo "RabbitMQ is healthy."
              break
            fi
            echo "Waiting..."
            sleep 5
          done
      - name: Run health checks on Scheduler
        run: |
          echo "Checking Scheduler service health"
          curl --fail http://localhost:8080/health || echo "Scheduler is not healthy"
      - name: List running containers
        run: docker ps
      - name: Terraform Destroy
        if: always()
        working-directory: terraform-local
        run: terraform destroy -auto-approve
            
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Run unit tests
        run: |
          docker-compose -f deployments/docker-compose.yml up --build --abort-on-container-exit

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Run integration test
        run: |
          set +e
          docker-compose -f deployments/docker-compose.integration.yml up --build --abort-on-container-exit
          EXIT_CODE=$?
          if [ "$EXIT_CODE" = "143" ]; then
            echo "Exited with 143 (SIGTERM) — treating as success"
            exit 0
          fi
          exit $EXIT_CODE
