name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build all services
        run: docker-compose build

      - name: Run test server
        run: docker-compose up --abort-on-container-exit --exit-code-from test-server test-server
